const router = require('express').Router()
const user = require('../controllers/user')
const product = require('../controllers/product')
const category = require('../controllers/category')
const branch = require('../controllers/branch')
const basket = require('../controllers/basket')
const sale = require('../controllers/sale')
const sendEmail = require('../controllers/sendEmail')

router.post('/createUser', user.createUser)
router.get('/getUser/:id', user.getUser)
router.post('/getUserByNameAndPassword', user.getUserByNameAndPassword)
router.put('/updateUser', user.updateUser)
router.delete('/deleteUser/:id', user.deleteUser)
router.post('/sendEmail', sendEmail.sendEmail)
router.post('/createProduct', product.createProduct)
router.get('/getAllProducts', product.getAllProducts)
router.delete('/deleteProduct/:id', product.deleteProduct)
router.get('/getAllcategories', category.getAllcategories)
router.post('/createCategory', category.createCategory)
router.post('/createBranch', branch.createBranch)
router.get('/getAllBranch', branch.getAllBranch)
router.get('/getBasketsByUserId/:id', basket.getBasketsByUserId)
router.post('/createBasket', basket.createBasket)
router.get('/getRelevantSales', sale.getCurrentSales)
router.post('/createSale', sale.createSale)
router.put('/updateProduct', product.updateProduct)


module.exports = router